name: Set-up LDC to target Linux AArch64
description: Adds a working aarch64-linux-android target to LDC.

runs:
  using: composite
  steps:
    - name: Set-up aarch64 cross-compilation
      shell: bash
      run: |
        mkdir -p $HOME/.ldc/
        LDC_VERSION=$(ldc2 --version | head -n 1 | grep -oE "[0-9][0-9]*\.[0-9][0-9]*\.[0-9][0-9]*")
        export DFLAGS="-gcc=$ANDROID_NDK/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android29-clang -linker=lld"
        cat << EOF | tee $HOME/.ldc/ldc2.conf
        "aarch64-.*-linux-android":
        {
            switches = [
                "-defaultlib=phobos2-ldc,druntime-ldc",
                "-gcc=$ANDROID_NDK/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android29-clang",
                "-linker=ld",
                "-L--sysroot=$ANDROID_NDK/toolchains/llvm/prebuilt/linux-x86_64/sysroot",
            ];
            post-switches = [
                "-I$HOME/ldc2-$LDC_VERSION-android-aarch64/import",
            ];
            lib-dirs = [
                "$HOME/ldc2-$LDC_VERSION-android-aarch64/lib",
            ];
        };
        EOF
        curl -LO https://github.com/ldc-developers/ldc/releases/download/v$LDC_VERSION/ldc2-$LDC_VERSION-android-aarch64.tar.xz
        tar -xf ./ldc2-$LDC_VERSION-android-aarch64.tar.xz -C $HOME
